### ISSUE TITLE
Are you planning to licence this project?

### ISSUE THREAD

**Issue by k5924** [jrdngr/pngme_book#15]
Hi, I just started working on pngme and was wondering if you could license the project? I know lots of people have probably already started implementing their own version of pngme, but I was wondering how you would like to be accredited?

**Comment by jrdngr** [comment]
You don't have to credit me at all.

**Comment by jrdngr** [comment]
I added a note to the README

**Comment by Coca162** [comment]
I'd suggest adding a proper license anyways since if you don't license your project you [technically retain complete exclusive copyright](https://choosealicense.com/no-permission/).

Since you are fine with not being credited at all, I'd suggest something like [Creative Commons Zero](https://creativecommons.org/public-domain/cc0/) which allows people to do whatever they want with this to the maximum extend allowed by the law.

**Comment by jrdngr** [comment]
Added CC0! Thanks for the suggestion!
